### GENERAL SETTINGS ###

# Site settings
title: Zulhilman Zakaria
description: "Welcome to my portfolio website"
analytics: UA-90544159-1
baseurl: "" #important: start with /
url: "http://yourdomain.com"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031" 
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.  
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"
  
  
### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: facebook
    url: https://www.facebook.com/Zoohilman
  - title: twitter
    url: https://www.twitter.com/Zoohilman
  - title: instagram
    url: https://www.instagram.com/Zoohilman

    
# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines: 
    - Shah Alam
    - Selangor
    - Malaysia.
email: Zulox93@gmail.com
tel: +34 8493-4893


